ASP.NET/Epione.Web/Controllers/PatientAppointmentController.cs
using Epione.Domain;
using Epione.Web.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Epione.Web.Controllers
{
    public class PatientAppointmentController : Controller
    {


        // to get all the appointments of the current user
        public async Task<ActionResult> ListAppointments()
        {

            var currentUser = (user)System.Web.HttpContext.Current.Session["IUser"];

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8089/epione-web/");

            // to get all the appointments of the current user

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("search/patientappointment/"+ currentUser.id).Result;

            var result = response.Content.ReadAsAsync<IEnumerable<appointment>>().Result;

            ViewBag.result = result;



            return View();
        }


        // add appointment

        




        [HttpPost]
        public async Task<ActionResult> CancelPatientAppointment(String id)
        {
            var request = new HttpRequestMessage(HttpMethod.Put,
       "http://localhost:8089/epione-web/appointment/"+id);
            var client = new HttpClient();
            //var json = JsonConvert.SerializeObject(user);
            //request.Content = new StringContent(json, Encoding.UTF8, "application/json");
            var response = await client.SendAsync(request);
        
                //Get Reponse content here
                return RedirectToAction("ListAppointments");

            
            //Error something went wrong
          
        }


        // view to update appointment

        public ActionResult PatientAppointmentToUpdate(String id, String specialtyname , String iddoctor)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8089/epione-web/");

            // to get the appointment selected

            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("appointment/byid/" + id).Result;

            var appointment = response.Content.ReadAsAsync<IEnumerable<appointment>>().Result;

            ViewBag.appointment = appointment;


            // to get all the motives from database for the update

            HttpResponseMessage response1 = client.GetAsync("search/motive/" + specialtyname).Result;

            var allmotives = response1.Content.ReadAsAsync<IEnumerable<motive>>().Result;

            ViewBag.motives = new SelectList(allmotives, "id", "name");

            ViewBag.allmotives = allmotives;

            
            // to get the docttor selected
            
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response2 = client.GetAsync("confirmed/" + iddoctor).Result;

            var doctor = response2.Content.ReadAsAsync<IEnumerable<user>>().Result;

            ViewBag.doctor = doctor;


            // to get all appointments of the doctor selected


            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response3 = client.GetAsync("search/appointment/" + iddoctor).Result;

            var listappointments = response3.Content.ReadAsAsync<IEnumerable<appointment>>().Result;

            ViewBag.listappointments = listappointments;



            


            // to get all the times from database to update  

            


            return View();
        }


 
        // Update appointment

       


        // to get all appointments by docotorId

        public ActionResult ListAppointmentByDoctorId()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8089/epione-web/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response1 = client.GetAsync("appointment/1").Result;

            var result1 = response1.Content.ReadAsAsync<IEnumerable<appointment>>().Result;

            ViewBag.result1 = result1;


            return View();
        }



        // to get all the treated appointments

        public async System.Threading.Tasks.Task<ActionResult> ListAppointmentsTreated()
        {
            var currentUser = (user)System.Web.HttpContext.Current.Session["IUser"];

            HttpClient client = new HttpClient();


            client.BaseAddress = new Uri("http://localhost:8089/epione-web/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("search/patientappointment/"+ currentUser.id).Result;

            var result = response.Content.ReadAsAsync<IEnumerable<appointment>>().Result;

            ViewBag.result = result;

            return View();
        }




    }




}

ASP.NET/Epione.Web/Views/PatientAppointment/ListAppointments.cshtml
@{
    ViewBag.Title = "ListAppointments";
}

<main>
    <div id="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Category</a></li>
                <li>Page active</li>
            </ul>
        </div>
    </div>
    <!-- /breadcrumb -->
    <div class="container margin_60">
        <div class="row justify-content-center">

            <h2>List of appointments in pending</h2>
            <br /><br /><br /><br />
            <table id="" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Motive</th>
                        <th>Message</th>
                        <th>Date</th>
                        <th>StartTime</th>
                        <th>EndTime</th>
                        <th>Doctor Name</th>
                        <th>Address</th>
                        <th>Actions</th>

                    </tr>
                </thead>
                <tbody>

                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        @*@using (Html.BeginForm("CancelPatientAppointment", "PatientAppointment", new { id = '1' }, FormMethod.Post, new { @Style = "display:none;" }))*@

                        @using (Html.BeginForm("CancelPatientAppointment", "PatientAppointment", FormMethod.Post, new { @Style = "display:none;" }))
                        {
                            <td> <a class="btn btn-warning" href="@Url.Action("UpdatePatientAppointment", "PatientAppointment")">Report</a> <button type="submit" class="btn btn-danger">Cancel</button></td>
                        }
                    </tr>

                </tbody>
            </table>
        </div>
    </div>

    <!-- /row -->
    <!-- /container -->
</main>

ASP.NET/Epione.Web/Views/PatientAppointment/ListAppointmentsTreated.cshtml
@{
    ViewBag.Title = "ListAppointmentsTreated";
}

<main>
    <div id="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Category</a></li>
                <li>Page active</li>
            </ul>
        </div>
    </div>
    <!-- /breadcrumb -->
    <div class="container margin_60">
        <div class="row justify-content-center">

            <h2>List of appointments in pending</h2>
            <br /><br /><br /><br />
            <table id="" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Motive</th>
                        <th>Message</th>
                        <th>Date</th>
                        <th>StartTime</th>
                        <th>EndTime</th>
                        <th>Doctor Name</th>
                        <th>Address</th>
                        <th>Actions</th>
                        <th></th>

                    </tr>
                </thead>


                <tbody>
                    @foreach (var r in ViewBag.result1)
                    {
                        if (@r.status == "treated")
                        {
                            <tr>
                                <td>@r.motive.name</td>
                                <td>@r.description</td>
                                <td>@r.date</td>
                                <td>@r.startTime</td>
                                <td>@r.endTime</td>
                                <td>@r.doctor.firstName  @r.doctor.lastName</td>
                                <td>@r.doctor.address</td>
                            </tr>
                        }
                    }
                </tbody>

            </table>
        </div>
    </div>

    <!-- /row -->
    <!-- /container -->
</main>