ASP.NET/Epione.Web/Controllers/ChatController.cs
using Epione.Service;
using Epione.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Epione.Domain;
using System.IO;
using Newtonsoft.Json;
using System.Net;
using Newtonsoft.Json.Converters;

namespace Epione.Web.Controllers
{

    public class ChatController : Controller
    {
        // GET: Chat
        public async Task<ActionResult> ChatBox()
        {
            ChatViewModel Model = new ChatViewModel();
            ServiceDiscussion serviceDiscussion = new ServiceDiscussion();
            Model.currentUser = (user) System.Web.HttpContext.Current.Session["IUser"];
            if (Model.currentUser == null)
            {
                return RedirectToAction("Login", "Home");
            }
            Model.discussions = await serviceDiscussion.getDiscussionsByIdUserAsync(Model.currentUser.id);
            return View(Model);
        }

        [HttpPost]
        [Route("Chat/DeleteConversation/{idConv}")]
        public ActionResult DeleteConversation(string idConv)
        {
            ServiceDiscussion serviceDiscussion = new ServiceDiscussion();
            user currentUser = (user)System.Web.HttpContext.Current.Session["IUser"];
            serviceDiscussion.deleteConversation(idConv, currentUser.id.ToString());
            return Json("Conversation deleted");
        }


        [HttpPost]
        public ActionResult UploadFile()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    //  Get all files from Request object  
                    HttpFileCollectionBase files = Request.Files;
                    //for (int i = 0; i < files.Count; i++)
                    //{
                        //string path = AppDomain.CurrentDomain.BaseDirectory + "Uploads/";  
                        //string filename = Path.GetFileName(Request.Files[i].FileName);  

                        HttpPostedFileBase file = files[0];
                        string fname, extension="";
                        

                        // Checking for Internet Explorer  
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            int index = file.FileName.LastIndexOf(".");
                            string name = file.FileName;
                            if (index > 0)
                            {
                                extension = name.Substring(index);
                            }
                            else// it's a record
                            {
                                if (name.Contains("blob"))
                                    extension = ".wav";
                        }

                            fname = Guid.NewGuid()+extension;
                        }

                        // save to the complete folder path and store the file inside it.  
                        file.SaveAs(Path.Combine(Server.MapPath("~/Content/Files/"), fname));
                        file.SaveAs("C:/root/Content/Files/" + fname);
                    //}
                    // Returns name of file uploaded  
                    return Json(fname);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else
            {
                return Json("No files selected.");
            }
        }

        

    }
}

ASP.NET/Epione.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Find easily a doctor and book online an appointment">

    <title>FINDOCTOR - Find easily a doctor and book online an appointment</title>
    <!-- Favicons-->
    <link rel="shortcut icon" href="~/Content/Front/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="~/Content/Front/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="~/Content/Front/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="~/Content/Front/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="~/Content/Front/img/apple-touch-icon-144x144-precomposed.png">
    <!-- BASE CSS -->
    <link href="~/Content/Front/css/bootstrap.min.css" rel="stylesheet">

    <!-- CSS FOR TEMPLATE CHAT -->
    <link href="~/Content/Chat/font-Source-Sans-Pro.css" rel="stylesheet" />
    <link rel="stylesheet prefetch" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link href="~/Content/Chat/fontawesome.min-5.5.0.all.css" rel="stylesheet" />
    <link href="~/Content/Chat/emojionearea.css" rel="stylesheet" />

    <!-- END CHAT -->

    <link href="~/Content/Front/css/style.css" rel="stylesheet">
    <link href="~/Content/Front/css/menu.css" rel="stylesheet">
    <link href="~/Content/Front/css/vendors.css" rel="stylesheet">
    <link href="~/Content/Front/css/icon_fonts/css/all_icons_min.css" rel="stylesheet">

    <!-- YOUR CUSTOM CSS -->
    <link href="~/Content/Chat/ChatStyle.css" rel="stylesheet" />
    <link href="~/Content/Chat/plyr.css" rel="stylesheet" />
    <link href="~/Content/Front/css/Doctolib.css" rel="stylesheet" />

    <link href="~/Content/Front/css/custom.css" rel="stylesheet">
    <link href="~/Content/Front/css/date_picker.css" rel="stylesheet">
    <link href="~/Content/Front/css/jquery.dataTables.min.css" rel="stylesheet">

    <!-- Modernizr -->
    <script src="~/Content/Front/js/modernizr.js"></script>




</head>
<body>
    <div class="layer"></div>
    <!-- Mobile menu overlay mask -->
    <div id="preloader">
        <div data-loader="circle-side"></div>
    </div>
    <!-- End Preload -->
    @Html.Partial("_NavigationBar")
    <!-- /header -->

    @RenderBody()
    <!-- /main content -->

    <footer>
        <div class="container margin_60_35">
            <div class="row">
                <div class="col-lg-3 col-md-12">
                    <p>
                        <a href="@Url.Action("Index","Home")" title="Findoctor">
                            <img src="~/Content/Front/img/logo.png" data-retina="true" alt="" width="163" height="36" class="img-fluid">
                        </a>
                    </p>
                </div>
                <div class="col-lg-3 col-md-4">
                    <h5>About</h5>
                    <ul class="links">
                        <li><a href="#0">About us</a></li>
                        <li><a href="blog.html">Blog</a></li>
                        <li><a href="#0">FAQ</a></li>
                        <li><a href="@Url.Action("Login","Home")">Login</a></li>
                        <li><a href="@Url.Action("RegisterDoctor","Home")">Register</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-4">
                    <h5>Useful links</h5>
                    <ul class="links">
                        <li><a href="#0">Doctors</a></li>
                        <li><a href="#0">Specialization</a></li>
                        <li><a href="#0">Join as a Doctor</a></li>
                        <li><a href="#0">Download App</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-4">
                    <h5>Contact with Us</h5>
                    <ul class="contacts">
                        <li><a href="tel://61280932400"><i class="icon_mobile"></i> + (216) 29 201 242</a></li>
                        <li><a href="mailto:epioneservice@gmail.com"><i class="icon_mail_alt"></i> EpioneService@Gmail.com</a></li>
                    </ul>
                    <div class="follow_us">
                        <h5>Follow us</h5>
                        <ul>
                            <li><a href="#0"><i class="social_facebook"></i></a></li>
                            <li><a href="#0"><i class="social_twitter"></i></a></li>
                            <li><a href="#0"><i class="social_linkedin"></i></a></li>
                            <li><a href="#0"><i class="social_instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--/row-->
            <hr>
            <div class="row">
                <div class="col-md-8">
                    <ul id="additional_links">
                        <li><a href="#0">Terms and conditions</a></li>
                        <li><a href="#0">Privacy</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <div id="copy">© 2017 Findoctor</div>
                </div>
            </div>
        </div>
    </footer>
    <!--/footer-->
    <div id="toTop"></div>
    <!-- Back to top button -->
    <!-- COMMON SCRIPTS -->
    @*<script src="~/Content/Front/js/jquery-2.2.4.min.js"></script>*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Content/Front/js/common_scripts.js"></script>
    <script src="~/Content/Front/js/functions.js"></script>
    <script src="~/Content/Front/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/Front/js/jquery.dataTables.min.js"></script>

    <!-- SPECIFIC SCRIPTS -->
    <script src="~/Content/Front/js/video_header.js"></script>

<!-- JS FOR TEMPLATE CHAT -->
    <script src="~/Scripts/Chat/emojionearea.js"></script>
    <script src="~/Scripts/Chat/popper.min.js"></script>
    @*<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>*@
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Chat/Recorder.js"></script>
    <script src="~/Scripts/Chat/plyr.polyfilled.js"></script>
   
<!-- END CHAT -->



@* redefine this section in your view  @Heythem mnasri ! *@
    @RenderSection("scripts", false);

    <script>
        'use strict';
        HeaderVideo.init({
            container: $('.header-video'),
            header: $('.header-video--media'),
            videoTrigger: $("#video-trigger"),
            autoPlayVideo: true
        });
    </script>

    <script>

        $('#calendar').datepicker({
            todayHighlight: true,
            daysOfWeekDisabled: [0],
            weekStart: 1,
            format: "yyyy-mm-dd",
            datesDisabled: ["2017/10/20", "2017/11/21", "2017/12/21", "2018/01/21", "2018/02/21", "2018/03/21"],
        });
    </script>

    <script>
        jQuery(document).ready(function () {
            jQuery('#annoncesTable').DataTable({
                "bPaginate": false,
                "info": false,
                "sDom": '<"pull-left"f><"pull-right"l>tip',


                // "aoColumns": [ {"bSearchable": false},{ "bSearchable": false }, { "bSearchable": true }, { "bSearchable": false }, { "bSearchable": false }, { "bSearchable": false }, { "bSearchable": false }, { "bSearchable": false }, ]
            });


        });
    </script>


</body>
</html>

ASP.NET/Epione.Web/Views/Shared/_LayoutTesting.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300" rel="stylesheet"
          type="text/css">

    <link rel="stylesheet prefetch" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="~/Content/Chat/emojionearea.css" rel="stylesheet" />
    <link href="~/Content/Chat/plyr.css" rel="stylesheet" />
    <link href="~/Content/Chat/ChatStyle.css" rel="stylesheet" />

</head>
<body>

    @RenderBody()
    <!-- /main content -->
    <!-- COMMON SCRIPTS -->
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/Chat/emojionearea.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.rawgit.com/mattdiamond/Recorderjs/08e7abd9/dist/recorder.js"></script>
    <script src="~/Scripts/Chat/plyr.polyfilled.js"></script>
    <script src="~/Scripts/Chat/ChatScript.js"></script>
    @RenderSection("scripts")
</body>
</html>

ASP.NET/Epione.Web/Views/Shared/_NavigationBar.cshtml
@using Epione.Domain;
@{
    var currentUser = (user)System.Web.HttpContext.Current.Session["IUser"];
}
<header class="header_sticky">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-6">
                <div id="logo_home">
                    <h1><a href="@Url.Action("Index","Home")" title="Findoctor">Findoctor</a></h1>
                </div>
            </div>
            <nav class="col-lg-9 col-6">
                <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="#0"><span>Menu mobile</span></a>
                <ul id="top_access">
                    @if (currentUser != null)
                    {
                        @*<li id="user">
                            <a href="#0">
                                <figure><img src="~/Content/Files/@currentUser.photo" alt="" width="150" height="150"></figure>
                                @currentUser.firstName @currentUser.lastName
                            </a>
                        </li>*@

                        
                    }
                    else
                    {
                        <li><a href="@Url.Action("Login", "Home")"><i class="pe-7s-user"></i></a></li>
            <li><a href="@Url.Action("RegisterDoctor", "Home")"><i class="pe-7s-add-user"></i></a></li>

                    }

                </ul>
                <div class="main-menu">
                    <ul>
                        <li class="submenu">
                            <a href="#0" class="show-submenu">Pages<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <li><a href="~/Content/Front/list.html">List page</a></li>
                                <li><a href="~/Content/Front/grid-list.html">List grid page</a></li>
                                <li><a href="~/Content/Front/list-map.html">List map page</a></li>
                                <li><a href="~/Content/Front/detail-page.html">Detail page</a></li>
                                <li><a href="~/Content/Front/detail-page-2.html">Detail page 2</a></li>
                                <li><a href="~/Content/Front/detail-page-3.html">Detail page 3</a></li>
                                <li><a href="~/Content/Front/blog-1.html">Blog</a></li>
                                <li><a href="~/Content/Front/badges.html">Badges</a></li>
                                <li><a href="~/Content/Front/login.html">Login</a></li>
                                <li><a href="~/Content/Front/login-2.html">Login 2</a></li>
                                <li><a href="~/Content/Front/register-doctor.html">Register Doctor</a></li>
                                <li><a href="~/Content/Front/register.html">Register</a></li>
                                <li><a href="~/Content/Front/contacts.html">Contacts</a></li>
                            </ul>
                        </li>
                        <li class="submenu">
                            <a href="#0" class="show-submenu">Extra Elements<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <li><a href="~/Content/Front/detail-page-working-booking.html">Detail working booking</a></li>
                                <li><a href="~/Content/Front/booking-page.html">Booking page</a></li>
                                <li><a href="~/Content/Front/confirm.html">Confirm page</a></li>
                                <li><a href="~/Content/Front/faq.html">Faq page</a></li>
                                <li><a href="~/Content/Front/coming_soon/index.html">Coming soon</a></li>
                                <li><a href="~/Content/Front/pricing-tables.html">Responsive pricing tables</a></li>
                                <li><a href="~/Content/Front/pricing-tables-2.html">Responsive pricing tables 2</a></li>
                                <li><a href="~/Content/Front/register-doctor-working.html">Working doctor register</a></li>
                                <li><a href="~/Content/Front/icon-pack-1.html">Icon pack 1</a></li>
                                <li><a href="~/Content/Front/icon-pack-2.html">Icon pack 2</a></li>
                                <li><a href="~/Content/Front/icon-pack-3.html">Icon pack 3</a></li>
                                <li><a href="~/Content/Front/404.html">404 page</a></li>
                            </ul>
                        </li>
                        <li class="submenu">
                        <a href="@Url.Action("ChatBox", "Chat")" class="show-submenu"> Messages
                            <i class="icon-chat"></i>
                        </a>
                        </li>
                        @if (currentUser != null)
                        {
                            <li class="submenu">
                                <a href="#0" class="show-submenu">
                                    <img src="/Content/Files/@currentUser.photo" alt="" width="30" height="30" style="
                                height: 30px;
                                width: 30px;
                                position: absolute;
                                border-radius: 50%;
                                right: 0;
                                margin: -5px -1px 0 0px;
                            ">
                                    @currentUser.firstName @currentUser.lastName <i class="icon-down-open-mini"></i>
                                </a>
                                <ul>
                                    <li><a href="@Url.Action("Index", "Home")">Edit profile</a></li>
                                    <li><a href="@Url.Action("Index", "Home")">Change credentils</a></li>
                                    <li><a href="@Url.Action("LogOff", "Home")">Log off</a></li>
                                    
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
                <!-- /main-menu -->
            </nav>
        </div>
    </div>
    <!-- /container -->
</header>