ASP.NET/Epione.Web/Models/DoctorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Epione.Web.Models
{
    public class SpecialityViewModel
    {
        public int id { get; set; }
        public string name { get; set; }
    }
    public class MotiveViewModel
    {
        public int id { get; set; }
        public string name { get; set; }
    }
    public class DoctorViewModel
    {
           public string firstName { get; set; }
     
        public string address { get; set; }

       
        public string lastName { get; set; }

         public string sexe { get; set; }

        public string civility { get; set; }

      
        public string email { get; set; }
     
        public string password { get; set; }
      
        public string phoneNumber { get; set; }
     
        public string licenseNumber { get; set; }

        public SpecialityViewModel specialty { get; set; }
        public IEnumerable<MotiveViewModel> motives { get; set; }


    }
}

ASP.NET/Epione.Web/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Epione.Domain;
using Epione.Domain.DTO;
using Epione.Service;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Epione.Web.Extensions;
using Epione.Web.Models;

namespace Epione.Web.Controllers
{
    public class DoctorController : Controller
    {
        ServiceUser _UserService;

        public DoctorController()
        {
            _UserService = new ServiceUser();
        }
        // GET: Doctor
        public async Task<ActionResult> Index()
        {
            List<DoctorDTO> doctors = await _UserService.getDoctorsList();

            //   return Json(doctors, JsonRequestBehavior.AllowGet);
            return View(doctors);
        }

        public async Task<ActionResult> Profile(int id)
        {
            DoctorDTO doctor = await _UserService.getDoctorByIdAsync(id);

             // return Json(doctor, JsonRequestBehavior.AllowGet);
            return View(doctor);
        }
    }
}

ASP.NET/Epione.Web/Views/Doctor/Index.cshtml
@model List<Epione.Domain.DTO.DoctorDTO>
@{
    
}


<main>
    <div>
        <div id="results">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <div class="search_bar_list">
                            <div class="tt-container">
                                <input id="Specialty" name="specialty" placeholder="Ex : dentist" required type="text" value="" class="form-control" />
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
    </div>
    <!-- /results -->

   
    <!-- /filters -->


    @*<div id="breadcrumb">
            <div class="container">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Category</a></li>
                    <li>Page active</li>
                </ul>
            </div>
        </div>*@
    <!-- /breadcrumb -->
    <div class="container margin_60_35">
        <div class="row">
            <div class="col-lg-12">

                <div class="row" id="list-of-doctors">
        @foreach(var Doctor in Model) { 
                    <div class="col-md-4">
                        <div class="box_list wow fadeIn animated" style="visibility: visible; animation-name: fadeIn;">
                            <figure>
                                <a href="@Url.Action("Profile", "Doctor", new { id = Doctor.id },null)">
                                    <img  src="/Content/Files/@Doctor.photo" class="img-fluid" alt="">
                                    <div class="preview"><span>Read more</span></div>
                                </a>
                            </figure>
                            <div class="wrapper">
                                <small>@Doctor.specialty.name</small>
                                <h3>Dr. @Doctor.firstName @Doctor.lastName</h3>

                                </div>
                            <ul>
                                <li><a href="@Url.Action("Profile", "Doctor", new { id = Doctor.id },null)" target="_blank"><i class="icon_pin_alt"></i>@Doctor.civility</a></li>
                                 <li><a href="#" target="_blank"><i class="icon_pin_alt"></i>Directions</a></li>

                                <li><a href="@Url.Action("Profile", "Doctor", new { id = Doctor.id },null)">Profile</a></li>
                            </ul>
                        </div>
                    </div>
        }
                    <!-- /box_list -->

                

                </div>
            </div>
        </div>
    </div>
</main>
            <!-- /box_general -->
@section Scripts {
    @Scripts.Render("~/bundles/typeahead")

    <script>
        $(document).ready(function () {
           

            var specialities = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                remote: {
                    url: 'http://localhost:8089/epione-web/specialty?name=%QUERY',
                    wildcard: '%QUERY'
                }
            });
            $('#Specialty').typeahead({
                minLength: 2,
                highlight: true
            }, {
                name: 'specialities',
                display: 'name',
                source: specialities,
                limit:100
            }).on("typeahead:select", function (e, element) {
                
                var value = element.name;
                

                    $.ajax({
                        url: "http://localhost:8089/epione-web/doctor?search=specialty.name&name=" + value,
                        dataType: "json",
                        type: "GET"
                    })
                      .done(function (result) {

                          $("#list-of-doctors").empty();


                          $.each(result, function (index, doctor) {
                              $("#list-of-doctors").append(
                             `<div class="col-md-4">
                        <div class="box_list wow fadeIn animated" style="visibility: visible; animation-name: fadeIn;">
                            <figure>
                                <a href="/Doctor/Profile/${doctor.id}">
                                    <img  src="/Content/Files/${doctor.photo}" class="img-fluid" alt="">
                                    <div class="preview"><span>Read more</span></div>
                                </a>
                            </figure>
                            <div class="wrapper">
                                <small>${doctor.specialty.name}</small>
                                <h3>Dr. ${doctor.firstName} ${doctor.lastName}</h3>

                                </div>
                            <ul>
                                <li><a href="/Doctor/Profile/${doctor.id}" target="_blank"><i class ="icon_pin_alt"></i>${doctor.civility}</a></li>
                                 <li><a href="#" target="_blank"><i class="icon_pin_alt"></i>Directions</a></li>

                                <li><a href="/Doctor/Profile/${doctor.id}">Profile</a></li>
                            </ul>
                        </div>
                    </div>`

                    );
                          })


                      })
                      .fail(function (msg) {
                          console.log(msg);
                      });

            });

        });

    </script>

}

ASP.NET/Epione.Web/Views/Doctor/profile.cshtml
@model Epione.Domain.DTO.DoctorDTO
@{

}


<main>
    @*<div id="breadcrumb">
            <div class="container">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Category</a></li>
                    <li>Page active</li>
                </ul>
            </div>
        </div>*@
    <!-- /breadcrumb -->

    <div class="container margin_60">
        <div class="row">
            <div class="col-xl-8 col-lg-8 offset-lg-2">
                <nav id="secondary_nav">
                    <div class="container">
                        <ul class="clearfix">
                            <li><a href="#section_1" class="active">General info</a></li>
                            <li><a href="#section_2"></a></li>
                            <li><a href="#sidebar"></a></li>

                        </ul>
                    </div>
                </nav>
                <div id="section_1">
                    <div class="box_general_3">
                        <div class="profile">
                            <div class="row">
                                <div class="col-lg-5 col-md-4">
                                    <figure>
                                        <img src="/Content/Files/@Model.photo" alt="" class="img-fluid">
                                    </figure>
                                </div>
                                <div class="col-lg-7 col-md-8">
                                    <small>@Model.specialty.name</small>
                                     <h1>Dr. @Model.firstName @Model.lastName</h1>
                                     <ul class="contacts">
                                        <li>
                                            <h6>Address</h6>
                                            <a href="#">@Model.address</a> 
                                        </li>
                                         <li>
                                             <h6>Phone</h6> <a href="#">@Model.phoneNumber</a>
                                         </li>
                                         <li>
                                             <h6>City</h6> <a href="#">@Model.civility</a>
                                         </li>
                                         <li>
                                             <h6>E-mail</h6> <a href="#">@Model.email</a>
                                         </li>
                                         <li>
                                             <h6>Sexe</h6> <a href="#">@Model.sexe</a>
                                         </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <hr>

                        <!-- /profile -->
                       
                        <div class="wrapper_indent">
                            <h6>Specializations @if (Model.motives.Count()==0) {<span>(none)</span> }</h6>
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="bullets">
                                        @foreach (var motive in Model.motives)
                                        {
                                            <li>@motive.name</li>

                                        }
                                       
                                    </ul>
                                </div>
                                
                            </div>
                            <!-- /row-->

                        </div>
                    </div>
                    <!--  /wrapper_indent -->
                </div>
                <!-- /section_1 -->
            </div>
        </div>
    </div>
</main>
<!-- /box_general -->