ASP.NET/Epione.Web/Controllers/AnalyticsController.cs
using Epione.Domain.Entities;
using Highsoft.Web.Mvc.Charts;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace Epione.Web.Controllers
{
    public class AnalyticsController : Controller
    {
        // GET: Analytics
        public ActionResult Index()
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8089");
            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            //pie chart
            HttpResponseMessage response = Client.GetAsync("Epione-web/rest/analytics/cancel/3").Result;
            var result = response.Content.ReadAsAsync<IEnumerable<JObject>>().Result;

            List<PieSeriesData> pieData = new List<PieSeriesData>();
            foreach (var r in result)
            {
                pieData.Add(new PieSeriesData
                {
                    Name = r.key,
                    Y = Convert.ToDouble(r.value, new CultureInfo("en-US"))
                });
            }
            ViewData["pieData"] = pieData;

            return View();
        }
        public IEnumerable<DateTime> EachDay(DateTime from, DateTime thru)
        {
            for (var day = from.Date; day.Date <= thru.Date; day = day.AddDays(1))
                yield return day;
        }
        public ActionResult Dashboard()
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8089");
            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


            DateTime toDay = DateTime.Now;
            HttpResponseMessage responseToday = Client.GetAsync("Epione-web/rest/analytics/next/3/day/" + toDay.ToString("yyyy-MM-dd")).Result;
            HttpResponseMessage responseDay1 = Client.GetAsync("Epione-web/rest/analytics/next/3/day/" + toDay.AddDays(1).ToString("yyyy-MM-dd")).Result;
            HttpResponseMessage responseDay2 = Client.GetAsync("Epione-web/rest/analytics/next/3/day/" + toDay.AddDays(2).ToString("yyyy-MM-dd")).Result;

            var resultToday = responseToday.Content.ReadAsAsync<IEnumerable<JObject>>().Result;
            var resultDay1 = responseDay1.Content.ReadAsAsync<IEnumerable<JObject>>().Result;
            var resultDay2 = responseDay2.Content.ReadAsAsync<IEnumerable<JObject>>().Result;

            foreach (var r in resultToday)
            {
                double rr = Convert.ToDouble(r.value, new CultureInfo("en-US"));
                ViewBag.vacationToday = rr;
            }
            foreach (var r in resultDay1)
            {
                double rr = Convert.ToDouble(r.value, new CultureInfo("en-US"));
                ViewBag.vacationDay1 = rr;
            }
            foreach (var r in resultDay2)
            {
                double rr = Convert.ToDouble(r.value, new CultureInfo("en-US"));
                ViewBag.vacationDay2 = rr;
            }
            ViewBag.toDay = toDay.ToString("yyyy-MM-dd");
            ViewBag.Day1 = toDay.AddDays(1).ToString("yyyy-MM-dd");
            ViewBag.Day2 = toDay.AddDays(2).ToString("yyyy-MM-dd");


            ViewBag.classSuccess = "success";
            ViewBag.classDanger = "danger";
            ViewBag.classWarning = "warning";

            HttpResponseMessage responseMostDay = Client.GetAsync("Epione-web/rest/analytics/most/3").Result;
            var resultMostDay = responseMostDay.Content.ReadAsAsync<IEnumerable<JObject>>().Result;


            List<int> numbersOccured = new List<int>();

            foreach (var d in resultMostDay)
            {
                numbersOccured.Add(Convert.ToInt32(d.value));
            }
            List<SplineSeriesData> DataOccured = new List<SplineSeriesData>();


            foreach (double value in numbersOccured)
            {
                SplineSeriesData data = new SplineSeriesData();
                data.Y = value;
                if (value == 26.5)
                {
                    data.Marker.Symbol = "url(http://www.highcharts.com/demo/gfx/sun.png)";
                }
                data.Drilldown = "time";
                DataOccured.Add(data);
            }

            ViewData["numbersOccured"] = DataOccured;

            DateTime date = new DateTime();
            var resultTimes = Enumerable.Repeat(date, 24)
                                   .Select((x, i) => x.AddHours(i).ToString("HH:tt"));
            ViewBag.listTimes = resultTimes;

            HttpResponseMessage responseNextPatient = Client.GetAsync("Epione-web/rest/analytics/next5Patient/3").Result;
            var resultNextPatient = responseNextPatient.Content.ReadAsAsync<IEnumerable<JObjectPatient>>().Result;
            ViewBag.resultNextPatient = resultNextPatient;

            return View();
        }
        public ActionResult Vacation(String option, String dateChosen)
        {
            ViewBag.dateChosen = dateChosen;
            ViewBag.option = option;
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8089");
            Client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            //LineTime chart
            int yearInt = Convert.ToInt32(dateChosen.Substring(0, 4));
            int monthInt = Convert.ToInt32(dateChosen.Substring(5, 2));
            int dayInt = Convert.ToInt32(dateChosen.Substring(8, 2));
            DateTime StartDate = new DateTime(yearInt, monthInt, dayInt);
            DateTime EndDate;
            if (option.Equals("day"))
            {
                EndDate = StartDate;
            }
            else if (option.Equals("week"))
            {
                EndDate = StartDate.AddDays(7);
            }
            else
            {
                EndDate = StartDate.AddMonths(1);
            }

            List<double> usedSlot = new List<double>();
            List<double> openSlot = new List<double>();
            List<double> notUsed = new List<double>();

            List<string> Categories = new List<string>();


            foreach (DateTime day in EachDay(StartDate, EndDate))
            {
                HttpResponseMessage response1 = Client.GetAsync("Epione-web/rest/analytics/3/day/" + day.ToString("yyyy-MM-dd")).Result;
                var result1 = response1.Content.ReadAsAsync<IEnumerable<JObject>>().Result;
                Categories.Add(day.ToString("yyyy-MM-dd"));

                foreach (var r in result1)
                {
                    if (Convert.ToDouble(r.value, new CultureInfo("en-US")) != 0.0)
                    {
                        if (r.key.Equals("usedSlots"))
                        {
                            usedSlot.Add(Convert.ToDouble(r.value, new CultureInfo("en-US")));
                        }
                        else if (r.key.Equals("openSlots"))
                        {
                            openSlot.Add(Convert.ToDouble(r.value, new CultureInfo("en-US")));
                        }
                        else
                        {
                            notUsed.Add(Convert.ToDouble(r.value, new CultureInfo("en-US")));
                        }
                    }
                }
            }




            List<ColumnSeriesData> johnData = new List<ColumnSeriesData>();
            List<ColumnSeriesData> janeData = new List<ColumnSeriesData>();
            List<ColumnSeriesData> joeData = new List<ColumnSeriesData>();

            usedSlot.ForEach(p => johnData.Add(new ColumnSeriesData { Y = p }));
            openSlot.ForEach(p => janeData.Add(new ColumnSeriesData { Y = p }));
            notUsed.ForEach(p => joeData.Add(new ColumnSeriesData { Y = p }));

            ViewData["johnData"] = johnData;
            ViewData["janeData"] = janeData;
            ViewData["joeData"] = joeData;
            ViewData["Categories"] = Categories;

            List<double> timeValues = usedSlot;


            List<AreaSeriesData> timeData = new List<AreaSeriesData>();
            timeValues.ForEach(p => timeData.Add(new AreaSeriesData { Y = p }));
            ViewBag.TimeData = timeData;


            return View();
        }
    }
}

ASP.NET/Epione.Web/Views/Analytics/Dashboard.cshtml
<script src="~/Content/Front/js/highcharts.js"></script>
<script src="~/Content/Front/js/exporting.js"></script>
<script src="~/Content/Front/js/offline-exporting.js"></script>

@{
    ViewBag.Title = "Dashboard";
}
@using Highsoft.Web.Mvc.Charts
<main>
    <div class="container margin_120_95">
        <div class="main_title">
            <div class="row">
                <div id="menuDashboadr" class="col-md-12 col-sm-12 main-menu">
                    <ul>
                        <li><a href="@Url.Action("Dashboard","Analytics")">Home</a></li>
                        <li class="submenu">
                            <a href="#0" class="show-submenu">Appointment<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <li><a href="@Url.Action("Index","AnalyticsAppointment")">General</a></li>
                                <li><a href="index-2.html">Home Version 2</a></li>
                            </ul>
                        </li>
                        <li class="submenu">
                            <a href="#0" class="show-submenu">Patient<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <li><a href="@Url.Action("Index","AnalyticsPatient")">General</a></li>
                                <li><a href="@Url.Action("PatientPerLocation","AnalyticsPatient")">Patient per location</a></li>
                            </ul>
                        </li>
                        <li class="submenu">
                            <a href="#0" class="show-submenu">Vacation<i class="icon-down-open-mini"></i></a>
                            <ul>
                                <li><a href="@Url.Action("Index","Analytics")">General</a></li>
                                <li><a href="/Analytics/Vacation/month/2018-10-10">Vacation per date</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <h3 class="text-center text-info">Vacation next 3 days</h3>
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="card" style="border-radius: 5px;margin-bottom: 30px;">
                    <div class="card-body">
                        <div class="p-10 no-block text-center">
                            <div class="align-slef-center">
                                <h2 class="m-b-0 text-@if (ViewBag.vacationToday >= 75){ @ViewBag.classSuccess ;}else if (ViewBag.vacationToday <= 25){ @ViewBag.classDanger ;}else{ @ViewBag.classWarning ;}">@ViewBag.vacationToday%</h2>
                                <h6>@ViewBag.toDay</h6>
                            </div>
                        </div>
                        <div class="progress" style="height: 4px;">
                            <div class="progress-bar bg-@if (ViewBag.vacationToday >= 75){ @ViewBag.classSuccess ;}else if (ViewBag.vacationToday <= 25){ @ViewBag.classDanger ;}else{ @ViewBag.classWarning ;}"
                                 role="progressbar" style="width: @ViewBag.vacationToday%" aria-valuenow="68" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="card" style="border-radius: 5px;margin-bottom: 30px;">
                    <div class="card-body">
                        <div class="p-10 no-block text-center">
                            <div class="align-slef-center">
                                <h2 class="m-b-0 text-@if (ViewBag.vacationDay1 >= 75){ @ViewBag.classSuccess ;}else if (ViewBag.vacationDay1 <= 25){ @ViewBag.classDanger ;}else{ @ViewBag.classWarning ;}">@ViewBag.vacationDay1%</h2>
                                <h6>@ViewBag.Day1</h6>
                            </div>
                        </div>
                        <div class="progress" style="height: 4px;">
                            <div class="progress-bar bg-@if (ViewBag.vacationDay1 >= 75){ @ViewBag.classSuccess ;}else if (ViewBag.vacationDay1 <= 25){ @ViewBag.classDanger ;}else{ @ViewBag.classWarning ;}" role="progressbar" style="width: @ViewBag.vacationDay1%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <br />
                    </div>
                </div>
            </div><div class="col-lg-4 col-md-6">
                <div class="card" style="border-radius: 5px;margin-bottom: 30px;">
                    <div class="card-body">
                        <div class="p-10 no-block text-center">
                            <div class="align-slef-center">
                                <h2 class="m-b-0 text-@if (ViewBag.vacationDay2 >= 75){ @ViewBag.classSuccess ;}else if (ViewBag.vacationDay2 <= 25){ @ViewBag.classDanger ;}else{ @ViewBag.classWarning ;}">@ViewBag.vacationDay2%</h2>
                                <h6>@ViewBag.Day2</h6>
                            </div>
                        </div>
                        <div class="progress" style="height: 4px;">
                            <div class="progress-bar  bg-@if (ViewBag.vacationDay2 >= 75){ @ViewBag.classSuccess ;}else if (ViewBag.vacationDay2 <= 25){ @ViewBag.classDanger ;}else{ @ViewBag.classWarning ;}" role="progressbar" style="width: @ViewBag.vacationDay2%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
        </div><div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h3 class="text-center text-info">Next 5 patients</h3>
                        <table id="myTable" class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Fullname</th>
                                    <th>Appointment date</th>
                                    <th>Appointment status</th>
                                    <th>Diagnosed before</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var obj in ViewBag.resultNextPatient)
                                {
                                    <tr>
                                        <td>@obj.fullName</td>
                                        <td>@obj.AppointmentDate</td>
                                        @if (obj.AppointmentStatus == "pending")
                                        {
                                            <td><span class="text-warning">Pending  <i class="fa fa-spinner fa-pulse"></i></span> </td>
                                        }
                                        else if (obj.AppointmentStatus == "cancelled")
                                        {
                                            <td><span class="text-danger">Cancelled  <i class="fa fa-times"></i></span> </td>
                                        }
                                        else
                                        {
                                            <td><span class="text-success">Treated  <i class="fa fa-check"></i></span> </td>
                                        }
                                        @if (obj.diagnosedBefore == "true")
                                        {
                                            <td>Yes</td>
                                        }
                                        else
                                        {
                                            <td><b>The first time</b></td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <span id="mostTime" class="fa fa-4x fa-clock-o"></span>

                        <div id="mostDayChart">
                            <script type="text/javascript">

                                function formatYAxisLabels() {
                                    return this.value;
                                }

                            </script>

                            @(Html.Highsoft().GetHighcharts(
new Highcharts
{
    Title = new Title
    {
        Text = "Most day occured"
    },
    XAxis = new List<XAxis>
    {
            new XAxis
            {
                Categories = new List<string> {
                        "Monday",
                        "Tuesday",
                        "Wednesday",
                        "Thursday",
                        "Friday",
                        "Saturday",
                        "Sunday" },
                Crosshair = new XAxisCrosshair
                {
                    Width = 1
                }
            }
    },
    YAxis = new List<YAxis>
    {
            new YAxis
            {
                Title = new YAxisTitle
                {
                    Text = "Number days"
                },
                Labels = new YAxisLabels
                {
                    Formatter = "formatYAxisLabels"
                },
                Crosshair = new YAxisCrosshair
                {
                    Width = 1
                }
            }
    },
    Tooltip = new Tooltip
    {
        Shared = true
    },
    PlotOptions = new PlotOptions
    {
        Spline = new PlotOptionsSpline
        {
            Marker = new PlotOptionsSplineMarker
            {
                Radius = 4,
                LineColor = "#666666",
                LineWidth = 1
            }
        },
        Series = {
            Animation =new Animation{ Duration = 1 ,Enabled=true}
        }
    },
    Series = new List<Series>
    {
            new SplineSeries
            {
                Name = "Occured",
                Data = @ViewData["numbersOccured"] as List<SplineSeriesData>,
            }
        }
}
    , "chart")
                            )
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
<!-- /main -->
<script>
    $("#mostTime").click(function () {
        var chart = $("#chart");
        chart.xAxis[0].setCategories(['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D']);
    });
</script>

ASP.NET/Epione.Web/Views/Analytics/Index.cshtml
<script src="~/Content/Front/js/highcharts.js"></script>
<script src="~/Content/Front/js/exporting.js"></script>
<script src="~/Content/Front/js/offline-exporting.js"></script>

@using System.Collections
@using Highsoft.Web.Mvc.Charts
@{
    ViewBag.Title = "Index";
}

<main>
    <div id="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Analytics</a></li>
                <li>Page active</li>
            </ul>
        </div>
    </div>

    <!-- /breadcrumb -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <!-- START USERS ACTIVITY BLOCK -->
                            <div class="panel panel-default">
                                <div class="panel-body padding-0">
                                    <div id="chart_div" width="400" height="250">

                                        @(Html.Highsoft().GetHighcharts(
        new Highcharts
        {
            Chart = new Highsoft.Web.Mvc.Charts.Chart
            {
                PlotBackgroundColor = null,
                PlotBorderWidth = null,
                PlotShadow = new Shadow
                {
                    Enabled = false
                }
            },
            Title = new Title
            {
                Text = "Browser market shares at a specific website, 2014"
            },
            Tooltip = new Tooltip
            {
                PointFormat = "{series.name}: <b>{point.percentage:.1f}%</b>"
            },
            PlotOptions = new PlotOptions
            {
                Pie = new PlotOptionsPie
                {
                    AllowPointSelect = true,
                    Cursor = PlotOptionsPieCursor.Pointer,
                    DataLabels = new PlotOptionsPieDataLabels
                    {
                        Enabled = false
                    },
                    ShowInLegend = true
                }
            },
            XAxis = new List<XAxis>
            {
                new XAxis
                {
                    Title = new XAxisTitle
                    {
                        Text = null
                    },
                    Categories = new List<string> { "Africa", "America", "Asia", "Europe", "Oceania" }
                }
            },
            YAxis = new List<YAxis>
            {
                new YAxis
                {
                    Min = 0,
                    Title = new YAxisTitle
                    {
                        Text = "Population (millions)",
                        Align = YAxisTitleAlign.High
                    }
                }
            },
            Series = new List<Series>
            {
                new PieSeries
                {
                    Name = "Percentage",
                    Data = @ViewData["pieData"] as List<PieSeriesData>
                },

            }
        }
        , "chart1")
                                        )

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <!-- START USERS ACTIVITY BLOCK -->
                            <div class="panel panel-default">
                                <div class="panel-body padding-0">
                                    <canvas id="pie_chart" width="400" height="250"></canvas>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- /row -->
    <!-- /container -->
</main>
<!-- /main -->

ASP.NET/Epione.Web/Views/Analytics/Vacation.cshtml
<script src="~/Content/Front/js/highcharts.js"></script>
<script src="~/Content/Front/js/exporting.js"></script>
<script src="~/Content/Front/js/offline-exporting.js"></script>

@{
    ViewBag.Title = "Vacation";
}

@using System.Collections
@using Highsoft.Web.Mvc.Charts
@{
    ViewBag.Title = "Index";
}

<main>
    <div id="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Analytics</a></li>
                <li>Page active</li>
            </ul>
        </div>
    </div>

    <!-- /breadcrumb -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4">
                            <select class="form-control " id="option" name="option">

                                <option @(ViewBag.option == "day" ? "selected" : string.Empty)
                                        value="day">
                                    Day
                                </option>
                                <option @(ViewBag.option == "week" ? "selected" : string.Empty)
                                        value="week">
                                    Week
                                </option>
                                <option @(ViewBag.option == "month" ? "selected" : string.Empty)
                                        value="month">
                                    Month
                                </option>
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <input value="@ViewBag.dateChosen" class="form-control bootstrap-datetimepicker-widget" type="date" id="dateChosen" name="dateChosen">
                        </div>
                        <div class="col-md-12">
                            <!-- START USERS ACTIVITY BLOCK -->
                            <div class="panel panel-default">
                                <div class="panel-body padding-0">
                                    @(Html.Highsoft().GetHighcharts(
        new Highcharts
        {
            Title = new Title
            {
                Text = "Percentage vacation"
            },
            XAxis = new List<XAxis>
            {
                new XAxis
                {
                    Categories = @ViewData["Categories"] as List<String>
                }
            },
            YAxis = new List<YAxis>
            {
                new YAxis
                {
                    Min = 0,
                    Title = new YAxisTitle
                    {
                        Text = "Total fruit consumption"
                    },
                    StackLabels = new YAxisStackLabels
                    {
                        Enabled = true,
                        Style = new YAxisStackLabelsStyle() { FontWeight = "bold" }
                    }
                }
            },
            Tooltip = new Tooltip
            {
                PointFormat = "<span style=\"color:{series.color}\">{series.name}</span>: <b>{point.y}</b> ({point.percentage:.0f}%)<br/>",
                Shared = true
            },
            PlotOptions = new PlotOptions
            {
                Column = new PlotOptionsColumn
                {
                    Stacking = PlotOptionsColumnStacking.Percent
                }
            },
            Series = new List<Series>
            {
                new ColumnSeries
                {
                    Name = "Not used slots",
                    Data = @ViewData["joeData"] as List<ColumnSeriesData>,
                    Color=@String.Format("#{0:X6}", new Random((int)DateTime.Now.Ticks).Next(0x1000000))
                },

                new ColumnSeries
                {
                    Name = "Used slots",
                    Data = @ViewData["johnData"] as List<ColumnSeriesData>,
                    Color=@String.Format("#{0:X6}", new Random((int)DateTime.Now.Ticks).Next(0x1010010))
                }
    }
        }
        , "chart")
                                    )

                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <!-- START USERS ACTIVITY BLOCK -->
                            <div class="panel panel-default">
                                <div class="panel-body padding-0">
                           @(Html.Highsoft().GetHighcharts(
        new Highcharts
        {
            Chart = new Highsoft.Web.Mvc.Charts.Chart
            {
                ZoomType = ChartZoomType.X
            },
            Title = new Title
            {
                Text = "Vacation evolution"
            },
            Subtitle = new Subtitle
            {
                Text = "Click and drag in the plot area to zoom in"
            },
            XAxis = new List<XAxis>
            {
                new XAxis
                {
                    Categories = @ViewData["Categories"] as List<String>
                }
            },
            YAxis = new List<YAxis>
            {
                new YAxis
                {
                    Title = new YAxisTitle
                    {
                        Text = "Number slots"
                    }
                }
            },
            Legend = new Legend
            {
                Enabled = false
            },
            PlotOptions = new PlotOptions
            {
                Series = new PlotOptionsSeries
                {
                    TurboThreshold = 10000
                },
                Area = new PlotOptionsArea
                {
                    ///FillColor = // TODO - LinerGradients
                    ///
                    Marker = new PlotOptionsAreaMarker
                    {
                        Radius = 2
                    },
                    LineWidth = 1,
                    States = new PlotOptionsAreaStates
                    {
                        Hover = new PlotOptionsAreaStatesHover
                        {
                            LineWidth = 1
                        }
                    },
                    Threshold = null
                }
            },
            Series = new List<Series>
            {
                new AreaSeries
                {
                    Name = "Used slots ",
                   
                    Data = @ViewBag.TimeData as List<AreaSeriesData>
                }
            }
        }
        , "chart1")
                        )
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
          </div>
    </div>
</div>
    <script>
        function randomColor() {
        var randomColor = '#' + ('000000' + Math.floor(Math.random() * 16777215).toString(16)).slice(-6);
                                }
        $('#dateChosen').change(function () {
            var option = $("#option").val();
            var date = $("#dateChosen").val();
            var from = date.split("/");
            var f = new Date(from[2], from[1], from[0]);
            var date_string = f.getFullYear() + "-" + f.getMonth() + "-" + f.getDate();
           
            window.location.href = "/Analytics/Vacation/" + option + "/" + date;
        });
        
    </script>

    <!-- /row -->
    <!-- /container -->
</main>
<!-- /main -->